services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - ${MQTT_UNENCRYPTED_PORT:-1883}:1883
      - ${MQTT_WEBSOCKET_PORT:-9001}:9001
    volumes:
      - ${MOSQUITTO_DATA_FOLDER:-./mosquitto/data}:/mosquitto/data:rw
      - ${MOSQUITTO_CONFIG_FOLDER:-./mosquitto/config}:/mosquitto/config:rw
      - ${MOSQUITTO_LOG_FOLDER:-./mosquitto/log}:/mosquitto/log:rw
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.2

networks:
  local:
    name: mqtt-local-network
    ipam:
      config:
        - subnet: 172.${SUBNET_NUMBER:-20}.0.0/16
