services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ${MOSQUITTO_DATA_FOLDER:-./mosquitto/data}:/mosquitto/data:rw
      - ${MOSQUITTO_CONFIG_FOLDER:-./mosquitto/config}:/mosquitto/config:rw
      - ${MOSQUITTO_LOG_FOLDER:-./mosquitto/log}:/mosquitto/log:rw
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${MQTT_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}